package com.fininsight.ai.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.time.Instant;
import java.util.Collections;
import java.util.List;

/**
 * Top-level response envelope for AI-powered financial insights and recommendations.
 */
@Schema(description = "AI financial insights response payload")
public record AiInsightResponse(
        @Schema(description = "Timestamp when insights were generated", example = "2026-08-23T22:00:00Z")
        Instant generatedAt,

        @Schema(description = "Executive summary of user's financial posture", example = "Your overall net balance is positive, though dining expenses saw a notable increase.")
        String summary,

        @Schema(description = "Categorized structured insights")
        List<AiInsightItem> insights,

        @Schema(description = "Actionable financial recommendations")
        List<String> recommendations,

        @Schema(description = "AI model identifier or engine name", example = "gpt-4o-mini")
        String model,

        @Schema(description = "True if generated by deterministic fallback engine due to AI unavailability", example = "false")
        boolean fallback,

        @Schema(description = "Mandatory educational / non-advisory legal disclaimer")
        String disclaimer,

        @Schema(description = "Correlation ID for request tracing", example = "a1b2c3d4-e5f6-7890-abcd-ef1234567890")
        String correlationId
) {
    public static final String DEFAULT_DISCLAIMER =
            "These insights are generated from your financial activity and are for informational purposes only. They do not constitute financial or investment advice.";

    public AiInsightResponse {
        generatedAt = generatedAt != null ? generatedAt : Instant.now();
        summary = summary != null ? summary : "";
        insights = insights != null ? Collections.unmodifiableList(insights) : Collections.emptyList();
        recommendations = recommendations != null ? Collections.unmodifiableList(recommendations) : Collections.emptyList();
        model = model != null ? model : "unknown";
        disclaimer = disclaimer != null ? disclaimer : DEFAULT_DISCLAIMER;
    }
}
