import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import { BrowserRouter } from 'react-router-dom';
import { AiInsightsPage } from '../pages/AiInsightsPage';
import { aiApi } from '../api/aiApi';
import { AiInsightResponse } from '../types/ai.types';
import { AxiosError, AxiosResponse, InternalAxiosRequestConfig } from 'axios';

vi.mock('../api/aiApi', () => ({
  aiApi: {
    getAiInsights: vi.fn(),
  },
}));

const mockAiResponse: AiInsightResponse = {
  generatedAt: '2026-08-23T14:30:00Z',
  summary: 'Your financial cash flow is healthy with steady income surplus.',
  insights: [
    {
      type: 'BUDGET_PACING',
      severity: 'WARNING',
      title: 'Dining Out Near Limit',
      description: 'You have spent 88% of your monthly dining budget.',
      recommendation: 'Cap dining out expenses to $50 for the remaining 8 days.',
    },
  ],
  recommendations: ['Increase automated monthly savings to $500', 'Review recurring subscription services'],
  model: 'gpt-4o-mini',
  fallback: false,
  disclaimer: 'This automated financial analysis is generated by AI for educational purposes only.',
};

describe('AiInsightsPage Integration', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renders executive summary, categorized insights, recommendations, and legal disclaimer', async () => {
    vi.mocked(aiApi.getAiInsights).mockResolvedValue(mockAiResponse);

    render(
      <BrowserRouter>
        <AiInsightsPage />
      </BrowserRouter>
    );

    expect(screen.getByText(/Synthesizing aggregated financial posture with AI/i)).toBeInTheDocument();

    await waitFor(() => {
      expect(screen.getByText('Your financial cash flow is healthy with steady income surplus.')).toBeInTheDocument();
      expect(screen.getByText('Dining Out Near Limit')).toBeInTheDocument();
      expect(screen.getByText('Increase automated monthly savings to $500')).toBeInTheDocument();
      expect(screen.getByText(/educational purposes only/i)).toBeInTheDocument();
      expect(screen.getByText(/Model: gpt-4o-mini/i)).toBeInTheDocument();
    });
  });

  it('gracefully notifies user when 429 Too Many Requests rate limit is hit', async () => {
    const error429 = new AxiosError(
      'Request failed with status code 429',
      'ERR_BAD_REQUEST',
      {} as InternalAxiosRequestConfig,
      {},
      {
        status: 429,
        statusText: 'Too Many Requests',
        data: { message: 'AI rate limit exceeded. Max 10 requests per minute.' },
        headers: {},
        config: {} as InternalAxiosRequestConfig,
      } as AxiosResponse
    );

    vi.mocked(aiApi.getAiInsights).mockRejectedValue(error429);

    render(
      <BrowserRouter>
        <AiInsightsPage />
      </BrowserRouter>
    );

    await waitFor(() => {
      expect(screen.getByText(/Rate Limit Exceeded/i)).toBeInTheDocument();
      expect(screen.getByText(/max 10 requests per minute/i)).toBeInTheDocument();
    });
  });

  it('renders fallback badge and warning note when backend returns fallback=true', async () => {
    const fallbackResponse: AiInsightResponse = {
      ...mockAiResponse,
      model: 'deterministic-rule-engine',
      fallback: true,
    };

    vi.mocked(aiApi.getAiInsights).mockResolvedValue(fallbackResponse);

    render(
      <BrowserRouter>
        <AiInsightsPage />
      </BrowserRouter>
    );

    await waitFor(() => {
      expect(screen.getByText(/Rule Engine Fallback/i)).toBeInTheDocument();
      expect(screen.getByText(/External AI provider is currently in fallback mode/i)).toBeInTheDocument();
    });
  });
});
