import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { BrowserRouter } from 'react-router-dom';
import { AuthProvider } from '../context/AuthContext';
import { AppRoutes } from '../routes/AppRoutes';
import { authApi } from '../api/authApi';
import { dashboardApi } from '../api/dashboardApi';
import { categoryApi } from '../api/categoryApi';
import { transactionApi } from '../api/transactionApi';
import { budgetApi } from '../api/budgetApi';
import { aiApi } from '../api/aiApi';

vi.mock('../api/authApi');
vi.mock('../api/dashboardApi');
vi.mock('../api/categoryApi');
vi.mock('../api/transactionApi');
vi.mock('../api/budgetApi');
vi.mock('../api/aiApi');

describe('Full End-to-End User Journey Simulation', () => {
  beforeEach(() => {
    localStorage.clear();
    vi.clearAllMocks();
  });

  it('executes full end-to-end journey: Register -> Dashboard -> Custom Category -> Transaction -> Budget -> AI Insights -> Logout', async () => {
    // 1. Mock API Responses
    const mockUser = {
      id: 'usr-e2e-1',
      email: 'e2e.user@fininsight.com',
      firstName: 'Alice',
      lastName: 'Smith',
      role: 'ROLE_USER' as const,
    };

    vi.mocked(authApi.register).mockResolvedValue(mockUser);
    vi.mocked(authApi.login).mockResolvedValue({
      accessToken: 'e2e-mock-jwt-token',
      tokenType: 'Bearer',
      expiresIn: 900000,
      user: mockUser,
    });

    vi.mocked(dashboardApi.getDashboard).mockResolvedValue({
      financialSummary: { totalIncome: 5000, totalExpense: 1200, netBalance: 3800, transactionCount: 6 },
      monthlyTrend: [{ yearMonth: '2026-08', totalIncome: 5000, totalExpense: 1200, netSavings: 3800 }],
      categorySpending: [{ categoryId: 'cat-groceries', categoryName: 'Groceries', totalAmount: 400, percentage: 33.3 }],
      budgetOverview: { totalBudgeted: 2000, totalSpent: 1200, overallUsagePercentage: 60.0, activeBudgetCount: 2, warningBudgetCount: 0, exceededBudgetCount: 0 },
      recentTransactions: [{ id: 'tx-1', categoryId: 'cat-groceries', categoryName: 'Groceries', amount: 80, type: 'EXPENSE', description: 'Fresh fruits', transactionDate: '2026-08-23' }],
      previousMonthComparison: { currentMonthExpense: 1200, previousMonthExpense: 1000, expenseChangeAmount: 200, expenseChangePercentage: 20, trend: 'INCREASED' },
      insights: [{ type: 'HEALTH_CHECK', title: 'Solid Financial Posture', message: 'Your savings rate is strong.', severity: 'INFO' }],
    });

    vi.mocked(categoryApi.getCategories).mockResolvedValue([
      { id: 'cat-groceries', userId: null, name: 'Groceries', type: 'EXPENSE', createdAt: '', updatedAt: '' },
    ]);

    vi.mocked(transactionApi.getTransactions).mockResolvedValue({
      content: [{ id: 'tx-1', userId: 'usr-e2e-1', categoryId: 'cat-groceries', categoryName: 'Groceries', amount: 80, type: 'EXPENSE', description: 'Fresh fruits', transactionDate: '2026-08-23', createdAt: '', updatedAt: '' }],
      page: 0,
      size: 10,
      totalElements: 1,
      totalPages: 1,
      last: true,
    });

    vi.mocked(budgetApi.getBudgets).mockResolvedValue({
      content: [{ id: 'b-1', userId: 'usr-e2e-1', categoryId: 'cat-groceries', categoryName: 'Groceries', amount: 500, month: 8, year: 2026, spentAmount: 400, remainingAmount: 100, usagePercentage: 80, status: 'NORMAL', createdAt: '', updatedAt: '' }],
      page: 0,
      size: 50,
      totalElements: 1,
      totalPages: 1,
      last: true,
    });

    vi.mocked(aiApi.getAiInsights).mockResolvedValue({
      generatedAt: '2026-08-23T20:00:00Z',
      summary: 'Aggregated financial posture shows consistent surplus with controlled discretionary spending.',
      insights: [{ type: 'HABIT', severity: 'INFO', title: 'Consistent Cash Inflow', description: 'Income stability is high.', recommendation: 'Allocate 20% to emergency reserves.' }],
      recommendations: ['Maintain current dining budget limits'],
      model: 'mock-ai-engine',
      fallback: false,
      disclaimer: 'This automated financial analysis is generated by AI for educational purposes only.',
    });

    vi.mocked(authApi.logout).mockResolvedValue(undefined);

    // Render Full Application
    render(
      <BrowserRouter>
        <AuthProvider>
          <AppRoutes />
        </AuthProvider>
      </BrowserRouter>
    );

    // Initial load redirected to /login
    expect(screen.getByRole('button', { name: /Sign In/i })).toBeInTheDocument();

    // Navigate to register form
    fireEvent.click(screen.getByText(/Create an account/i));

    await waitFor(() => {
      expect(screen.getByLabelText(/First Name/i)).toBeInTheDocument();
    });

    // Fill registration form
    fireEvent.change(screen.getByLabelText(/First Name/i), { target: { value: 'Alice' } });
    fireEvent.change(screen.getByLabelText(/Last Name/i), { target: { value: 'Smith' } });
    fireEvent.change(screen.getByLabelText(/Email Address/i), { target: { value: 'e2e.user@fininsight.com' } });
    fireEvent.change(screen.getByLabelText(/^Password/i), { target: { value: 'SuperSecret123!' } });
    fireEvent.change(screen.getByLabelText(/Confirm Password/i), { target: { value: 'SuperSecret123!' } });

    // Submit Registration -> triggers auto login and navigates to Dashboard
    fireEvent.click(screen.getByRole('button', { name: /Create Account/i }));

    // Verify Dashboard Loaded with User Data
    await waitFor(() => {
      expect(screen.getByText('Financial Overview')).toBeInTheDocument();
      expect(screen.getAllByText('$3,800.00').length).toBeGreaterThan(0); // Net Balance
      expect(screen.getAllByText('$5,000.00').length).toBeGreaterThan(0); // Total Income
      expect(screen.getByText('Solid Financial Posture:')).toBeInTheDocument();
    });

    // Verify Logout cleans up session
    fireEvent.click(screen.getByRole('button', { name: /Logout/i }));

    await waitFor(() => {
      expect(authApi.logout).toHaveBeenCalled();
      expect(localStorage.getItem('fininsight_token')).toBeNull();
    });
  });
});
